### ISSUE TITLE
After a while, no more pulses are counted

### ISSUE THREAD

**Issue by Herbi-1966** [iotdevicesdev/GGreg20_V3-ESP32-HomeAssistant-ESPHome#4]
The topic is a bit old, but I haven't found a solution yet and have put the Geiger counter aside.

It seems as if the ESP32's memory fills up after a while and no more pulses are counted. Unfortunately, I'm not an expert in programming the ESP32.

I already have a new GGREG20_V3 module, swapped the tube for a new one and tried several ESP32 modules.

The GGREG20_V3 modules and the tubes work, the LED flashes and the acoustic signal can be heard.

Perhaps one of you has a solution, I don't know what to do next.

Many thanks and kind regards
Herbi
(please also PM me, if possible)

**Comment by iotdevicesdev** [comment]
Hello, @Herbi-1966! Thank you for your message and feedback! 

This is the first time I've heard of this issue. It is very interesting.

I suggest we correspond here, so that the community can also benefit from our shared experience with this issue.
Please leave your full YAML code here (no personal data is required, of course), and include the name of your ESP32 board and information about its manufacturer and model point. 

It will be very helpful if you indicate how you connected the GGreg20_V3 and your ESP32 board. I am interested in understanding all the connections (signals, power and common ground).

Also, please indicate which version of ESPHome and Home Assistant you are using, both firmware and environment. 

I will take a look in detail what I can recommend you to try to do.

Best regards,
Oleksii

**Comment by Herbi-1966** [comment]
Hello Oleksii,

Thank you for your quick reply. I have done some more intensive research on the internet and found out that this effect (no counting of pulses by the ESP32 after a while) does occur. It is recommended that if the effect occurs after a few days/weeks, you should disconnect the ESP32 for a few minutes. A side note then links to the Homeassistant Community/radiation-detector-platform/ and here to the topic 'Pin Reuse validation'.

I already knew this site, I chose "Way 2" (...allow_other_uses: true...) when updating because it seemed easier and quicker to me at the time.

Now I have flashed the "Way 1" (... platform: copy ... source_id: my_cpm_meter ...) variant and it has been working perfectly fine so far.

I have also connected a Zigbee socket in front of it in case the ESP32 hangs :-).

The wiring ESP32 > GGREG20_V3 module is exactly as described on your homepage.
My YAML file corresponds to the one on the homepage, my ESP module: FCC ID:2AC7Z-ESP32WROOM32.

Thank you again! I'll be in touch again in a while to report...

All the best and kind regards
Herbi

**Comment by Herbi-1966** [comment]
Hello,
it's been almost a month now and everything is working perfectly.
I never had to unplug the ESP32.
Apparently there was a mistake in my previous variant "Way 2" as described above.
Anyway, thank you for your support.

Best regards
Herbi

**Comment by iotdevicesdev** [comment]
Hello!
I'm very glad that everything is working fine. 
I know that the ESP8266 has to reboot every 15 minutes due to some incompatibility in the WiFi drivers with the ESPHome firmware (and they did it automatically). For example, there is no such problem with ESP8266 with NodeMCU/Lua firmware. 

As for the ESP32, I haven't heard of it needing to be restarted either.

BR,
Oleksii
